### ISSUE TITLE
Add Filter Plugin

### ISSUE THREAD

**Issue by takus** [takus/fluent-plugin-ec2-metadata#13]
http://docs.fluentd.org/articles/filter-plugin-overview

**Comment by howarddierking** [comment]
+1 - I can see tremendous value in using this plugin. However, I need to use it in conjunction with https://github.com/ryotarai/fluent-plugin-cloudwatch-logs and I'm not sure how to set this up without using this plugin as a filter.

**Comment by takus** [comment]
Released this feature in v0.10.0
