### ISSUE TITLE
unexpected error error="execution expired"

### ISSUE THREAD

**Issue by rohitrsh** [takus/fluent-plugin-ec2-metadata#30]
Hi Takus,

I am getting subjected error while, adding metadata using ec2-metadata plugin. Its working fine for me on the instances, expose to internet (member of public subnet).

On my instance which where i am getting error, i am able to access ec2 metadata services using curl, also during fluentd startup i have captured network dump, where also i was able to see its successfully able to fetch matadata from metadata service. However still giving me above error.

Kindly help let me know, what other services it uses while fetching ec2-metadata.

I am attaching config/error as attachment.

[ec2-metadata_issue.txt](https://github.com/takus/fluent-plugin-ec2-metadata/files/674154/ec2-metadata_issue.txt)

-Rohit

**Comment by takus** [comment]
Sorry for the late response.

For resolving `${tagset_name}`, this plugin requests to AWS API. According to your stack trace, the request to AWS API failed. Does your instance have connectivity to the Internet? Without connectivity to AWS API, this plugin can't resolve `${tagset_xxx}`.

**Comment by rohitrsh** [comment]
Thanks, after removing `${tagset_name}` its working fine for me.

-Rohit
