### ISSUE TITLE
Should yank 0.0.16? 

### ISSUE THREAD

**Issue by cosmo0920** [takus/fluent-plugin-ec2-metadata#33]
Because 0.0.16 contains breaking changes which cause runtime error to use with Fluentd v0.12.
Fluentd plugin upgrade guide says that fluentd plugins which are updating for v0.14 from v0.12 should bump major or minor version up.
ref: http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12#2-update-dependency

### Expected

* yank 0.0.16 and release 0.1.0 once again
* Fluentd v0.12 users can continue to use v0.12 series of Fluentd with `~> 0.0.15` syntax  in their plugin management Gemfile.

### Actual

* only patch level version up (0.0.15 -> 0.0.16)

**Comment by takus** [comment]
Yanked in #34
