### ISSUE TITLE
Use without aws permissions

### ISSUE THREAD

**Issue by Trane9991** [takus/fluent-plugin-ec2-metadata#37]
Hey,
as far as I see from code AWS IAM permissions `ec2:DescribeInstances` only to read instance tags.

But even if I don't use tags in the message plugin still needs the IAM Permission, would be much better if it is required only when you use the tags in messages.

**Comment by takus** [comment]
Unless you use `tagset_*` in your configuration, the plugin doesn't use EC2 client and IAM permissions are not necessary.

https://github.com/takus/fluent-plugin-ec2-metadata/blob/eed88578a00e221666fdc31bfe1bcda262939af6/lib/fluent/plugin/ec2_metadata.rb#L82
