### ISSUE TITLE
Fluentd >= 1.0 throw warnings on configurations

### ISSUE THREAD

**Issue by Trane9991** [takus/fluent-plugin-ec2-metadata#38]
Hello,
I just noticed that fluentd keep complaining about configurations for this module:
`2018-03-12 13:36:48 +0000 [warn]: section <record> is not used in <filter ***> of ec2_metadata plugin`
or 
`parameter 'output_tag' in <filter ***> is not used.`

but it is still needed. This is pretty confusing.

Config example:
```
<filter ***>
  @type ec2_metadata
  metadata_refresh_seconds 300
  output_tag ${tag}
  <record>
    instance_id ${instance_id}
    instance_type ${instance_type}
    private_ip ${private_ip}
  </record>
</filter>
```

**Comment by cosmo0920** [comment]
In filter version of ec2_metadata plugin, you needn't to use `output_tag` parameter.
Filter plugin cannot modify tag in record.
And I send [a PR](#39) to fix `[warn]: section <record> is not used in <filter ***> of ec2_metadata plugin` warnings.

**Comment by Trane9991** [comment]
@cosmo0920 many thanks. 
Are you going to release gem `v1.1.2`?

**Comment by cosmo0920** [comment]
`v0.1.2` will be released soon by @takus.
