### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by igalarzab** [takus/fluent-plugin-ec2-metadata#44]
Can this plugin create nested fields, so the ec2 metadata is not spread through the `_source`, but everything is created inside of a nested object?

This:

```json
{
   "ec2": {
        "ip": "1.2.3.4",
        "az": "eu-west-1"
    }
}
```

Instead of this:

```json
{
   "ec2_ip":  "1.2.3.4",
   "ec2_az": "eu-west-1"
}
```

This is the current configuration we have, but it's not nesting the output:

```ruby
<filter **>
    @type ec2_metadata

    <record>
        ec2.instance_id   ${instance_id}
        ec2.private_ip    ${private_ip}
        ec2.az            ${availability_zone}
    </record>
</filter>
```

Thanks!

**Comment by cosmo0920** [comment]
This feature is not supported.
